// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Greet: typeof import('./src/components/Greet.vue')['default']
    Operate: typeof import('./src/components/Operate.vue')['default']
    Screenshot: typeof import('./src/components/Screenshot.vue')['default']
  }
}
